export interface IndexEntry {
  agent: string;
  organization: string;
  benchmark: string;
  benchmarkCategory: "WEB NAV" | "RESEARCH" | "DESKTOP" | "CODING" | "TOOL USE" | "GENERAL" | "SPECIALIZED";
  score: string;
  scoreNum: number;
  source: string;
  selfReported: boolean;
  openSource: boolean;
  isNew?: boolean;
}

export const indexEntries: IndexEntry[] = [

  // WEBVOYAGER
  { agent: "Surfer 2",          organization: "H Company",        benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "97.1%",  scoreNum: 97.1,  source: "https://hcompany.ai/surfer-2",                                                          selfReported: true,  openSource: false, isNew: true },
  { agent: "Magnitude",         organization: "Magnitude",        benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "93.9%",  scoreNum: 93.9,  source: "https://magnitude.run/webvoyager",                                                      selfReported: true,  openSource: true,  isNew: true },
  { agent: "AIME Browser-Use",  organization: "Aime",             benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "92.34%", scoreNum: 92.34, source: "https://aime-browser-use.github.io/",                                                   selfReported: true,  openSource: false, isNew: true },
  { agent: "Surfer-H + Holo1",  organization: "H Company",        benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "92.2%",  scoreNum: 92.2,  source: "https://arxiv.org/pdf/2506.02865",                                                      selfReported: false, openSource: false, isNew: true },
  { agent: "Browserable",       organization: "Browserable",      benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "90.4%",  scoreNum: 90.4,  source: "https://www.browserable.ai/blog/web-voyager-benchmark",                                 selfReported: true,  openSource: true,  isNew: true },
  { agent: "Browser Use",       organization: "Browser Use",      benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "89.1%",  scoreNum: 89.1,  source: "https://browser-use.com/posts/sota-technical-report",                                   selfReported: true,  openSource: true  },
  { agent: "Operator",          organization: "OpenAI",           benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "87.0%",  scoreNum: 87.0,  source: "https://openai.com/index/introducing-operator/",                                        selfReported: true,  openSource: false },
  { agent: "Skyvern 2.0",       organization: "Skyvern",          benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "85.85%", scoreNum: 85.85, source: "https://blog.skyvern.com/skyvern-2-0-state-of-the-art-web-navigation/",                  selfReported: true,  openSource: true  },
  { agent: "Project Mariner",   organization: "Google",           benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "83.5%",  scoreNum: 83.5,  source: "https://deepmind.google/technologies/project-mariner/",                                 selfReported: true,  openSource: false },
  { agent: "Agent-E",           organization: "Emergence AI",     benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "73.1%",  scoreNum: 73.1,  source: "https://www.emergence.ai/blog/agent-e-sota",                                             selfReported: true,  openSource: false },
  { agent: "Proxy Lite",        organization: "Convergence AI",   benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "72.4%",  scoreNum: 72.4,  source: "https://convergence.ai/proxy-lite",                                                     selfReported: true,  openSource: false },
  { agent: "WebSight",          organization: "Academic",         benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "68.0%",  scoreNum: 68.0,  source: "https://arxiv.org/abs/2508.16987",                                                      selfReported: false, openSource: true  },
  { agent: "Runner H 0.1",      organization: "H Company",        benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "67.0%",  scoreNum: 67.0,  source: "https://www.hcompany.ai/blog/a-research-update",                                        selfReported: true,  openSource: false },
  { agent: "WebVoyager",        organization: "Academic",         benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "59.1%",  scoreNum: 59.1,  source: "https://arxiv.org/abs/2401.13919",                                                      selfReported: false, openSource: true  },
  { agent: "WILBUR",            organization: "Academic",         benchmark: "WebVoyager",         benchmarkCategory: "WEB NAV",  score: "53.0%",  scoreNum: 53.0,  source: "https://arxiv.org/abs/2404.05902",                                                      selfReported: false, openSource: false },

  // WEBARENA
  { agent: "DeepSeek v3.2",     organization: "DeepSeek",         benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "74.3%",  scoreNum: 74.3,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: false, openSource: true,  isNew: true },
  { agent: "OpAgent",           organization: "CodeFuse AI",      benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "71.6%",  scoreNum: 71.6,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: false, openSource: true  },
  { agent: "ColorBrowserAgent", organization: "ColorBrowser",     benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "71.2%",  scoreNum: 71.2,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: false, openSource: true  },
  { agent: "Claude Code + GBOX","organization": "GBOX AI",        benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "68.0%",  scoreNum: 68.0,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: false, openSource: false },
  { agent: "DeepSky Agent",     organization: "DeepSky",          benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "66.9%",  scoreNum: 66.9,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: true,  openSource: false },
  { agent: "Narada AI",         organization: "Narada",           benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "64.2%",  scoreNum: 64.2,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: true,  openSource: false },
  { agent: "IBM CUGA",          organization: "IBM",              benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "61.7%",  scoreNum: 61.7,  source: "https://arxiv.org/abs/2502.18438",                                                      selfReported: false, openSource: false },
  { agent: "OpenAI Operator",   organization: "OpenAI",           benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "58.1%",  scoreNum: 58.1,  source: "https://openai.com/index/introducing-operator/",                                        selfReported: true,  openSource: false },
  { agent: "Jace.AI",           organization: "Jace AI",          benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "57.1%",  scoreNum: 57.1,  source: "https://jace.ai/blog/awa-1-5-achieves-breakthrough-performance",                        selfReported: true,  openSource: false },
  { agent: "WebOperator+GPT-4o","organization": "WebOperator",    benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "54.6%",  scoreNum: 54.6,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: false, openSource: true  },
  { agent: "ScribeAgent+GPT-4o","organization": "Scribe",         benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "53.0%",  scoreNum: 53.0,  source: "https://scribehow.com/library/scribe-agent",                                            selfReported: false, openSource: false },
  { agent: "AgentSymbiotic",    organization: "Academic",         benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "52.1%",  scoreNum: 52.1,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: false, openSource: true  },
  { agent: "Learn-by-Interact", organization: "Academic",         benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "48.0%",  scoreNum: 48.0,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: false, openSource: true  },
  { agent: "AgentOccam-Judge",  organization: "Academic",         benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "45.7%",  scoreNum: 45.7,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: false, openSource: true  },
  { agent: "WebPilot",          organization: "WebPilot",         benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "37.2%",  scoreNum: 37.2,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: false, openSource: false },
  { agent: "GUI-API Hybrid",    organization: "Academic",         benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "35.8%",  scoreNum: 35.8,  source: "https://docs.google.com/spreadsheets/d/1M801lEpBbKSNwP-vDBkC_pF7LdyGU1f_ufZb_NWNBZQ", selfReported: false, openSource: true  },
  { agent: "AWM",               organization: "Academic",         benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "35.5%",  scoreNum: 35.5,  source: "https://arxiv.org/abs/2409.07429",                                                      selfReported: false, openSource: true  },
  { agent: "Magentic-One",      organization: "Microsoft",        benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "30.5%",  scoreNum: 30.5,  source: "https://arxiv.org/abs/2411.04468",                                                      selfReported: false, openSource: true  },
  { agent: "GPT-4 baseline",    organization: "OpenAI",           benchmark: "WebArena",           benchmarkCategory: "WEB NAV",  score: "14.9%",  scoreNum: 14.9,  source: "https://arxiv.org/abs/2307.13854",                                                      selfReported: false, openSource: false },

  // ONLINE-MIND2WEB
  { agent: "SeeAct + GPT-5",    organization: "Academic",         benchmark: "Online-Mind2Web",    benchmarkCategory: "WEB NAV",  score: "42.33%", scoreNum: 42.33, source: "https://hal.cs.princeton.edu/online_mind2web",                                          selfReported: false, openSource: true,  isNew: true },
  { agent: "Browser-Use",       organization: "Browser Use",      benchmark: "Online-Mind2Web",    benchmarkCategory: "WEB NAV",  score: "40.00%", scoreNum: 40.0,  source: "https://hal.cs.princeton.edu/online_mind2web",                                          selfReported: false, openSource: true  },
  { agent: "SeeAct + o3",       organization: "Academic",         benchmark: "Online-Mind2Web",    benchmarkCategory: "WEB NAV",  score: "39.00%", scoreNum: 39.0,  source: "https://hal.cs.princeton.edu/online_mind2web",                                          selfReported: false, openSource: true  },

  // BROWSECOMP
  { agent: "Kimi K2 Thinking",  organization: "Moonshot AI",      benchmark: "BrowseComp",         benchmarkCategory: "RESEARCH", score: "60.2%",  scoreNum: 60.2,  source: "https://moonshotai.github.io/Kimi-K2/",                                                 selfReported: true,  openSource: true,  isNew: true },
  { agent: "Deep Research",     organization: "OpenAI",           benchmark: "BrowseComp",         benchmarkCategory: "RESEARCH", score: "51.5%",  scoreNum: 51.5,  source: "https://openai.com/index/browsecomp/",                                                  selfReported: true,  openSource: false },
  { agent: "WebSailor-72B",     organization: "Academic",         benchmark: "BrowseComp",         benchmarkCategory: "RESEARCH", score: "12.0%",  scoreNum: 12.0,  source: "https://arxiv.org/pdf/2507.02592",                                                      selfReported: false, openSource: true  },
  { agent: "GPT-4o + browsing", organization: "OpenAI",           benchmark: "BrowseComp",         benchmarkCategory: "RESEARCH", score: "1.9%",   scoreNum: 1.9,   source: "https://openai.com/index/browsecomp/",                                                  selfReported: true,  openSource: false },

  // GAIA
  { agent: "h2oGPTe Agent",     organization: "H2O.ai",           benchmark: "GAIA",               benchmarkCategory: "GENERAL",  score: "75.0%",  scoreNum: 75.0,  source: "https://h2o.ai/blog/2025/h2o-ai-tops-the-general-ai-assistant-test/",                  selfReported: true,  openSource: false, isNew: true },
  { agent: "Manus",             organization: "Manus AI",         benchmark: "GAIA",               benchmarkCategory: "GENERAL",  score: "~75.0%", scoreNum: 74.9,  source: "https://huggingface.co/spaces/gaia-benchmark/leaderboard",                              selfReported: false, openSource: false },
  { agent: "Deep Research",     organization: "OpenAI",           benchmark: "GAIA",               benchmarkCategory: "GENERAL",  score: "67.36%", scoreNum: 67.36, source: "https://openai.com/index/introducing-deep-research/",                                   selfReported: true,  openSource: false },
  { agent: "MS Research (o1)",  organization: "Microsoft",        benchmark: "GAIA",               benchmarkCategory: "GENERAL",  score: "38.0%",  scoreNum: 38.0,  source: "https://huggingface.co/spaces/gaia-benchmark/leaderboard",                              selfReported: false, openSource: false },
  { agent: "HF Agents",         organization: "Hugging Face",     benchmark: "GAIA",               benchmarkCategory: "GENERAL",  score: "33.0%",  scoreNum: 33.0,  source: "https://huggingface.co/spaces/gaia-benchmark/leaderboard",                              selfReported: false, openSource: true  },
  { agent: "GPT-4 + tools",     organization: "OpenAI",           benchmark: "GAIA",               benchmarkCategory: "GENERAL",  score: "15.0%",  scoreNum: 15.0,  source: "https://huggingface.co/spaces/gaia-benchmark/leaderboard",                              selfReported: false, openSource: false },

  // OSWORLD
  { agent: "AskUI VisionAgent", organization: "AskUI",            benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "66.2%",  scoreNum: 66.2,  source: "https://www.askui.com/benchmarks",                                                      selfReported: true,  openSource: false, isNew: true },
  { agent: "Agent S3",          organization: "Simular AI",       benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "69.9%",  scoreNum: 69.9,  source: "https://github.com/simular-ai/Agent-S",                                                 selfReported: false, openSource: true,  isNew: true },
  { agent: "CoACT-1",           organization: "USC / Salesforce", benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "60.76%", scoreNum: 60.76, source: "https://arxiv.org/abs/2508.00000",                                                      selfReported: false, openSource: true  },
  { agent: "Agent S2.5 w/ o3",  organization: "Simular AI",       benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "56.0%",  scoreNum: 56.0,  source: "https://github.com/simular-ai/Agent-S",                                                 selfReported: false, openSource: true  },
  { agent: "GTA1 w/ o3",        organization: "Salesforce",       benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "53.1%",  scoreNum: 53.1,  source: "https://arxiv.org/pdf/2507.05791",                                                      selfReported: false, openSource: false },
  { agent: "OpenAI CUA (o3)",   organization: "OpenAI",           benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "42.9%",  scoreNum: 42.9,  source: "https://xlang.ai/blog/osworld-verified",                                                selfReported: false, openSource: false },
  { agent: "UI-TARS-1.5",       organization: "ByteDance",        benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "42.5%",  scoreNum: 42.5,  source: "https://xlang.ai/blog/osworld-verified",                                                selfReported: false, openSource: true  },
  { agent: "Agent S2 w/ Gemini","organization": "Simular AI",     benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "41.4%",  scoreNum: 41.4,  source: "https://github.com/simular-ai/Agent-S",                                                 selfReported: false, openSource: true  },
  { agent: "OpenAI CUA (4o)",   organization: "OpenAI",           benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "31.4%",  scoreNum: 31.4,  source: "https://xlang.ai/blog/osworld-verified",                                                selfReported: false, openSource: false },
  { agent: "Claude 3.7 (CU)",   organization: "Anthropic",        benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "28.0%",  scoreNum: 28.0,  source: "https://xlang.ai/blog/osworld-verified",                                                selfReported: false, openSource: false },
  { agent: "UI-TARS-1.5 (29%)", organization: "ByteDance",        benchmark: "OSWorld",            benchmarkCategory: "DESKTOP",  score: "29.6%",  scoreNum: 29.6,  source: "https://xlang.ai/blog/osworld-verified",                                                selfReported: false, openSource: true  },

  // ANDROIDWORLD
  { agent: "Agent S3",          organization: "Simular AI",       benchmark: "AndroidWorld",       benchmarkCategory: "DESKTOP",  score: "66.8%",  scoreNum: 66.8,  source: "https://github.com/simular-ai/Agent-S",                                                 selfReported: false, openSource: true,  isNew: true },
  { agent: "AskUI AndroidVA",   organization: "AskUI",            benchmark: "AndroidWorld",       benchmarkCategory: "DESKTOP",  score: "64.8%",  scoreNum: 64.8,  source: "https://www.askui.com/benchmarks",                                                      selfReported: true,  openSource: false },
  { agent: "M3A (Gemini 1.5)",  organization: "Google DeepMind",  benchmark: "AndroidWorld",       benchmarkCategory: "DESKTOP",  score: "30.0%",  scoreNum: 30.0,  source: "https://arxiv.org/abs/2405.14573",                                                      selfReported: false, openSource: false },

  // SWE-BENCH
  { agent: "OpenAI o3",         organization: "OpenAI",           benchmark: "SWE-bench Verified", benchmarkCategory: "CODING",   score: "~72.0%", scoreNum: 72.0,  source: "https://openai.com/index/early-access-to-o3/",                                          selfReported: true,  openSource: false, isNew: true },
  { agent: "Claude 3.7 Sonnet", organization: "Anthropic",        benchmark: "SWE-bench Verified", benchmarkCategory: "CODING",   score: "~62.0%", scoreNum: 62.0,  source: "https://www.anthropic.com/research/swe-bench-sonnet",                                   selfReported: true,  openSource: false },
  { agent: "Devin 2.0",         organization: "Cognition",        benchmark: "SWE-bench Verified", benchmarkCategory: "CODING",   score: "~55.0%", scoreNum: 55.0,  source: "https://cognition.ai/blog/devin-2",                                                     selfReported: true,  openSource: false },
  { agent: "Gru",               organization: "Mutable AI",       benchmark: "SWE-bench Verified", benchmarkCategory: "CODING",   score: "~57.0%", scoreNum: 57.0,  source: "https://mutable.ai/blog/swe-bench",                                                     selfReported: true,  openSource: false },

  // MLE-BENCH
  { agent: "AIDE (Claude 3.5)", organization: "Anthropic",        benchmark: "MLE-bench",          benchmarkCategory: "CODING",   score: "~17% medals", scoreNum: 17.0, source: "https://arxiv.org/abs/2410.07095",                                              selfReported: false, openSource: false },

  // GPQA DIAMOND
  { agent: "o3",                organization: "OpenAI",           benchmark: "GPQA Diamond",       benchmarkCategory: "GENERAL",  score: "~87.0%", scoreNum: 87.0,  source: "https://openai.com/index/early-access-to-o3/",                                          selfReported: true,  openSource: false },
  { agent: "Gemini 2.5 Pro",    organization: "Google",           benchmark: "GPQA Diamond",       benchmarkCategory: "GENERAL",  score: "~86.0%", scoreNum: 86.0,  source: "https://deepmind.google/technologies/gemini/",                                          selfReported: true,  openSource: false },
  { agent: "Claude 3.7 Sonnet", organization: "Anthropic",        benchmark: "GPQA Diamond",       benchmarkCategory: "GENERAL",  score: "~84.0%", scoreNum: 84.0,  source: "https://www.anthropic.com/claude/claude-3-7-sonnet",                                    selfReported: true,  openSource: false },

  // ARC-AGI-2
  { agent: "o3 (high)",         organization: "OpenAI",           benchmark: "ARC-AGI-2",          benchmarkCategory: "GENERAL",  score: "~4.0%",  scoreNum: 4.0,   source: "https://arcprize.org/arc-agi-2",                                                        selfReported: false, openSource: false },
  { agent: "Gemini 2.5 Pro",    organization: "Google",           benchmark: "ARC-AGI-2",          benchmarkCategory: "GENERAL",  score: "~2.0%",  scoreNum: 2.0,   source: "https://arcprize.org/arc-agi-2",                                                        selfReported: false, openSource: false },

  // TOOLBENCH
  { agent: "ToolLLaMA-v2",      organization: "Academic",         benchmark: "ToolBench",          benchmarkCategory: "TOOL USE", score: "~60.0%", scoreNum: 60.0,  source: "https://arxiv.org/abs/2307.16789",                                                      selfReported: false, openSource: true  },
  { agent: "GPT-4",             organization: "OpenAI",           benchmark: "ToolBench",          benchmarkCategory: "TOOL USE", score: "~54.0%", scoreNum: 54.0,  source: "https://arxiv.org/abs/2307.16789",                                                      selfReported: false, openSource: false },
  { agent: "Claude 3 Opus",     organization: "Anthropic",        benchmark: "ToolBench",          benchmarkCategory: "TOOL USE", score: "~49.0%", scoreNum: 49.0,  source: "https://arxiv.org/abs/2307.16789",                                                      selfReported: false, openSource: false },

  // AGENTBENCH
  { agent: "GPT-4",             organization: "OpenAI",           benchmark: "AgentBench",         benchmarkCategory: "GENERAL",  score: "4.27",   scoreNum: 4.27,  source: "https://arxiv.org/abs/2308.03688",                                                      selfReported: false, openSource: false },
  { agent: "Claude 2",          organization: "Anthropic",        benchmark: "AgentBench",         benchmarkCategory: "GENERAL",  score: "3.51",   scoreNum: 3.51,  source: "https://arxiv.org/abs/2308.03688",                                                      selfReported: false, openSource: false },
  { agent: "GPT-3.5-turbo",     organization: "OpenAI",           benchmark: "AgentBench",         benchmarkCategory: "GENERAL",  score: "2.01",   scoreNum: 2.01,  source: "https://arxiv.org/abs/2308.03688",                                                      selfReported: false, openSource: false },
];

export const indexBenchmarks = [...new Set(indexEntries.map(e => e.benchmark))].sort();
export const indexCategories = ["ALL", "WEB NAV", "RESEARCH", "DESKTOP", "CODING", "TOOL USE", "GENERAL", "SPECIALIZED"] as const;